cleanup

diff --git a/ips/post5g b/ips/post5g
--- a/ips/post5g
+++ b/ips/post5g
@@ -2,7 +2,7 @@
 
 # Function to display usage information
 usage() {
-  echo "Usage: $0 experiment [get|launch|prefix] <experiment_name> [--release]"
+  echo "Usage: $0 experiment [get|launch|prefix|cleanup] <experiment_name> [--release]"
   echo "       $0 nodes [start|stop] <node_name>"
   exit 1
 }
@@ -38,8 +38,6 @@ stop_node(){
   "state": "OFF"
   }'
 }
-
-xp_expauth.ilabt.imec.be_01jazhwr8yfcf8p811ezqry6z9
 
 get_experiment_id(){
   local experiment_name="$1"
@@ -87,6 +85,7 @@ get_experiment() {
   experiment_id=$(get_experiment_id $experiment_name)
 
   echo $experiment_id
+  echo "$experiment_id" | sed 's/.*_\([a-z0-9]*\)/\1/'
 
   DIR=xp/$project_id/$experiment_name/
 
@@ -99,7 +98,11 @@ get_experiment() {
 
 
   TOKEN="$(slices auth id-token pos)"
-  curl -s -X GET "https://post5g-backend.slices-be.eu/pos/script/${experiment_id}"   -H 'accept: application/json' -H "Bearer: ${TOKEN}" --output ${experiment_id}.zip
+  status_code=$(curl -s -X GET "https://post5g-backend.slices-be.eu/pos/script/${experiment_id}" -w "%{http_code}"  -H 'accept: application/json' -H "Bearer: ${TOKEN}" --output ${experiment_id}.zip)
+  if [ $status_code -ne 200 ]; then
+    echo "Experiment not found" >&2
+    exit 1
+  fi
   unzip -qq -o -d reference_implementation-develop/ ${experiment_id}.zip
   chmod a+r -R reference_implementation-develop/
 
@@ -122,8 +125,25 @@ launch_experiment() {
   pos/deploy.sh
 }
 
+cleanup() {
+  local project_id="$1"
+  local experiment_name="$2"
 
+  TOKEN="$(slices auth id-token pos)"
+  XP_TOKEN="$(slices experiment jwt $experiment_name)"
 
+  status_code=$(curl -o $$.log -s -w "%{http_code}" -X 'POST' "https://post5g-backend.slices-be.eu/cleanup/"   -H 'accept: application/json' -H 'Content-Type: application/json' -H "Bearer: ${TOKEN}" -d "{\"token\": \"$XP_TOKEN\"}")
+  if [ $status_code -ne 200 ]; then
+    echo "Error while cleaning" >&2
+    cat $$.log
+    rm $$.log
+    exit 1
+  fi
+
+  cat $$.log
+  rm $$.log
+  release_prefix "$project_id" "$experiment_name"
+}
 
 #########
 # Check that the correct number of arguments are passed
@@ -161,6 +181,9 @@ if [ "$type" == "experiment" ]; then
       ;;
     launch)
       launch_experiment "$project_id" "$experiment_name"
+      ;;
+    cleanup)
+      cleanup "$project_id" "$experiment_name"
       ;;
     prefix)
       # get_prefix "$project_id" "$experiment_name"
